Add support for Django 3.2
stefanfoulis/django-phonenumber-field pull request #419
Opened 2021-02-13 13:21 UTC by francoisfreitag

2021-02-13 16:39 UTC, stefanfoulis requested changes

2021-02-13 16:39 UTC, stefanfoulis commented on tox.ini
> +    dj31: Django>=3.2,<3.3
```suggestion
    dj32: Django>=3.2,<3.3
```

2021-02-13 19:36 UTC, francoisfreitag commented on tox.ini
> +    dj31: Django>=3.2,<3.3
:eyes: Thanks!

2021-02-13 19:55 UTC, francoisfreitag commented
This PR has to wait until 3.2 is actually out.

2021-03-19 16:48 UTC, stefanfoulis approved these changes

2021-03-22 09:51 UTC, merged